### ISSUE TITLE
Add split-pane toggle setting

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#22]
See https://github.com/exercism/exercism/issues/4735

- Add a setting for `full_width_code_panes` which is set to `false` by default. (Similar to how dark code theme works)
- Add UI to settings similarly to the "dark code theme". Change the `h2` heading on the settings bit from "Dark Code Theme" to say "Code Viewing Options" and add an extra switch.
- When it is set to be `true` add a class to the `tabs-and-panes` for `full-width` in the various places it occurs around the site.
- Have some CSS like:
```scss
.tabs-and-panes.full-width {
  .lhs, .rhs { width: 100% }
  .lhs { margin-bottom;20px; }
  .rhs { padding-left: 0px; }
  .widget-discussion-post img { max-width: 50px }
}
```

You'll make a *lot* of people happy with this :)
